# This file is used to configure the Render deployment.
services:
  - type: web
    name: my-app
    env: node
    plan: free
    buildCommand: cd server && yarn install && yarn build
    startCommand: cd server && yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://tree-app-react.onrender.com
