services:
  - type: web
    name: my-app
    env: node
    plan: free
    buildCommand: cd server && npm install && npm run client-install && npm run client-build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://tree-app-react.onrender.com
